

baseURL = 'https://plomeroquito24h.com/'
languageCode = 'es-es'
title = 'Plomero Quito - Servicios 24/7'

[params]
telefono = "0992560478"
whatsapp = "593992560478"
direccion = "Quito, Ecuador"
horario = "Atenci√≥n 24/7"
empresa = "Plomero Quito"
