

baseURL = 'https://plomeroquito.com/'
languageCode = 'es-es'
title = 'Plomero Quito - Servicios 24/7'

[params]
telefono = "0980277855"
whatsapp = "593980277855"
direccion = "Quito, Ecuador"
horario = "Atenci√≥n 24/7"
empresa = "Plomero Quito"